name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.13.0
    - run: opam pin add -n .
    - run: opam depext -yt methml
    - run: opam install -t .
